env:
  global:
    - CC_TEST_REPORTER_ID=bfe1331818a2cea90bc5dde922a6aba5753c65b63bb46ad63b970eb24fb0cc5e
    
sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.0
      env: setup=lowest
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest

before_install:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo

install:
  - |
    if [[ "$setup" == "stable" ]]; then
      travis_retry composer update --prefer-dist --no-scripts --no-interaction --prefer-stable --no-suggest;
    fi
    if [[ "$setup" == "lowest" ]]; then
      travis_retry composer update --prefer-dist --no-scripts --no-interaction --prefer-lowest --prefer-stable --no-suggest;
    fi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - composer test

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "7.0" && "$setup" == "stable" ]]; then
      travis_retry composer require --dev satooshi/php-coveralls
      
      vendor/bin/coveralls -v
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    fi
